### ISSUE TITLE
TZCronJob not found EKS 1.23

### ISSUE THREAD

**Issue by kickthemooon** [hiddeco/cronjobber#56]
I am trying to get cronjobber running on EKS 1.23

The error:

```
Unable to update status for production/test-cronjob (rv = 8509036): tzcronjobs.cronjobber.hidde.co "test-cronjob" not found
```

Stacktrace:

```
github.com/hiddeco/cronjobber/pkg/controller/cronjobber.syncOne
	/go/src/github.com/hiddeco/cronjobber/pkg/controller/cronjobber/controller.go:257
github.com/hiddeco/cronjobber/pkg/controller/cronjobber.(*TZCronJobController).syncAll
	/go/src/github.com/hiddeco/cronjobber/pkg/controller/cronjobber/controller.go:146
github.com/hiddeco/cronjobber/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/src/github.com/hiddeco/cronjobber/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
github.com/hiddeco/cronjobber/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/src/github.com/hiddeco/cronjobber/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
github.com/hiddeco/cronjobber/vendor/k8s.io/apimachinery/pkg/util/wait.Until
	/go/src/github.com/hiddeco/cronjobber/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
```

Any ideas?

**Comment by kickthemooon** [comment]
for some reason I removed the status subresource in the CRD during conversion to v1

```
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tzcronjobs.cronjobber.hidde.co
spec:
  conversion:
    strategy: None
  group: cronjobber.hidde.co
  names:
    kind: TZCronJob
    listKind: TZCronJobList
    plural: tzcronjobs
    shortNames:
      - tzc
    singular: tzcronjob
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The schedule defining the interval a TZCronJob is run
          jsonPath: .spec.schedule
          name: Schedule
          type: string
        - description: The time zone the interval of a TZCronJob is calculated in
          jsonPath: .spec.timezone
          name: Time zone
          type: string
        - description: The last time a Job was scheduled by a TZCronJob
          jsonPath: .status.lastScheduleTime
          name: Last schedule
          type: date
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
```

After adding it back the error was gone
