### ISSUE TITLE
Update the timezone db periodically

### ISSUE THREAD

**Issue by mterron** [hiddeco/cronjobber#9]
Maybe it'd be a good idea to periodically (using CronJobs 😉?) run a script to update the timezone db instead of mounting the host one. That way CronJobber would not depend on the host having a timezone db at all.

**Comment by hiddeco** [comment]
_Something_ that takes care of this is welcome as a PR.

I am not sure if a `CronJob` would be the way as I think it can be tricky to update the contents of something that is already mounted and running (by the controller).

**Comment by mterron** [comment]
What requirements/constraints do you want to work with? 
How about something like this `deploy.yaml` :
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjobber
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cronjobber
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: cronjobber
    spec:
      serviceAccountName: cronjobber
      securityContext:
        fsGroup: 65534 #nobody
      volumes:
      - name: timezonedb
        emptyDir: {}
      containers:
      - name: cronjobber
        image: quay.io/hiddeco/cronjobber:0.1.1
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        args:
        - --log-level=info
        volumeMounts:
        - name: timezonedb
          mountPath: /usr/share/zoneinfo
          readOnly: true
      - name: updatetz
        image: mterron/updatetz
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: timezondb
          mountPath: /tmp/zoneinfo
```
`mterron/updatetz` is a container I published on DockerHub that unpacks an up to date tzdata into the persistent volume.
